### ISSUE TITLE
Questions about dataset preprocessing

### ISSUE THREAD

**Issue by YCC-324** [papersPapers/BadPrompt#2]
Hello, I wonder how you generate the file "target_all_subj.csv"

**Comment by becomeGiant** [comment]
Hello, I have the same problem. Did you solve it?

**Comment by YCC-324** [comment]
@becomeGiant 

Sorry, I didn't get the file.

**Comment by papersPapers** [comment]
Sorry for missing your question. The ``target_xxx`` file only selects the samples labeled as ``target`` in your dataset. For format issues, you can refer to the file in ``trigger_generation`` we uploaded.
